/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soft_adi_famous_instagram_Global */

#ifndef _Included_com_midnight_healthcare_Global
#define _Included_com_midnight_healthcare_Global
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soft_adi_famous_instagram_Global
 * Method:    HelloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_midnight_healthcare_Global_HelloJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
